# Special configuration section for Chunk Wands

# This is the time the player will wait after they add a chunk to the queue for it to be removed
chunk-removal-delay: 5

# The number of blocks that will be removed at one time by the plugin
# Higher number = more lag / faster chunk removal, lower number = less lag / slower chunk removal
removal-grouping-size: 80

# The delay, in ticks, between the groupings of blocks being removed
# Smaller number = more lag / faster chunk removal, higher number = less lag / slower chunk removal
delay-between-grouping-removal: 5

# Blocks that will not be removed by the chunk wands
buster-block-blacklist:
  - bedrock
  - mob_spawner
  - hopper
  - chest
  - trapped_chest
  - glass
  - dispenser
  - dropper
  - ender_portal_frame
  - ender_portal
  - ender_chest
  - web
